/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import java.awt.CardLayout;
import java.awt.Component;
import java.awt.geom.RoundRectangle2D;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import bd.Conexion;
import java.sql.PreparedStatement;
import menu_principal.MenuPrincipal;

/**
 *
 * @author carto
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    CardLayout cardlayout;
    public String nUsuario;
    public Login() {
        setUndecorated(true);
        initComponents();
        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 20, 20));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topHead = new javax.swing.JPanel();
        btnCerrar = new javax.swing.JButton();
        btnIngresar = new javax.swing.JButton();
        btnRegistrarse = new javax.swing.JButton();
        cards = new javax.swing.JPanel();
        pnlIngresar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jpsPass = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        btnOlvidar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jtUsuario = new javax.swing.JTextField();
        btnAcceder = new javax.swing.JButton();
        pnlRegistrar = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtUsuarioC = new javax.swing.JTextField();
        jtNombreC = new javax.swing.JTextField();
        jtEmailC = new javax.swing.JTextField();
        jtPassC = new javax.swing.JTextField();
        btnRegistrarseC = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        topHead.setBackground(new java.awt.Color(255, 255, 255));
        topHead.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                topHeadMouseDragged(evt);
            }
        });
        topHead.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                topHeadMousePressed(evt);
            }
        });
        topHead.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesLogin/close.png"))); // NOI18N
        btnCerrar.setBorderPainted(false);
        btnCerrar.setContentAreaFilled(false);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        topHead.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, -1, -1));

        btnIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesLogin/btnIngresarActivo.png"))); // NOI18N
        btnIngresar.setBorderPainted(false);
        btnIngresar.setContentAreaFilled(false);
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        topHead.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        btnRegistrarse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesLogin/btnRegistrarsInac.png"))); // NOI18N
        btnRegistrarse.setBorderPainted(false);
        btnRegistrarse.setContentAreaFilled(false);
        btnRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarseActionPerformed(evt);
            }
        });
        topHead.add(btnRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        getContentPane().add(topHead, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 60));

        cards.setBackground(new java.awt.Color(255, 255, 255));
        cards.setLayout(new java.awt.CardLayout());

        pnlIngresar.setBackground(new java.awt.Color(255, 255, 255));
        pnlIngresar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesLogin/imgLoginUser.png"))); // NOI18N
        pnlIngresar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, -10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesLogin/user.png"))); // NOI18N
        pnlIngresar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, 40));

        jpsPass.setText("$$$$$$$$$$$$$");
        jpsPass.setBorder(null);
        jpsPass.setEchoChar('\u2022');
        jpsPass.setOpaque(false);
        jpsPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jpsPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jpsPassFocusLost(evt);
            }
        });
        pnlIngresar.add(jpsPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 220, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesLogin/user.png"))); // NOI18N
        pnlIngresar.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, 40));

        btnOlvidar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesLogin/¿Olvidó su contraseña.png"))); // NOI18N
        btnOlvidar.setBorderPainted(false);
        btnOlvidar.setContentAreaFilled(false);
        btnOlvidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOlvidarActionPerformed(evt);
            }
        });
        pnlIngresar.add(btnOlvidar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, -1, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesLogin/Rectangle abajo.png"))); // NOI18N
        pnlIngresar.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, -1, -1));

        jtUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtUsuario.setText("E-mail");
        jtUsuario.setBorder(null);
        jtUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtUsuarioFocusLost(evt);
            }
        });
        pnlIngresar.add(jtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 220, 40));

        btnAcceder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesLogin/btnAcceder.png"))); // NOI18N
        btnAcceder.setBorderPainted(false);
        btnAcceder.setContentAreaFilled(false);
        btnAcceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccederActionPerformed(evt);
            }
        });
        pnlIngresar.add(btnAcceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 310, 130, 40));

        cards.add(pnlIngresar, "card3");

        pnlRegistrar.setBackground(new java.awt.Color(255, 255, 255));
        pnlRegistrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesLogin/user.png"))); // NOI18N
        pnlRegistrar.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesLogin/Formulario de Registro.png"))); // NOI18N
        pnlRegistrar.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 180, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesLogin/user.png"))); // NOI18N
        pnlRegistrar.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesLogin/user.png"))); // NOI18N
        pnlRegistrar.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, 40));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesLogin/user.png"))); // NOI18N
        pnlRegistrar.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, 40));

        jtUsuarioC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtUsuarioC.setText("Nombre de Usuario");
        jtUsuarioC.setBorder(null);
        jtUsuarioC.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtUsuarioCFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtUsuarioCFocusLost(evt);
            }
        });
        pnlRegistrar.add(jtUsuarioC, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 220, 40));

        jtNombreC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtNombreC.setText("Nombre y Apellido");
        jtNombreC.setBorder(null);
        jtNombreC.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtNombreCFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtNombreCFocusLost(evt);
            }
        });
        pnlRegistrar.add(jtNombreC, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 220, 40));

        jtEmailC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtEmailC.setText("E-mail");
        jtEmailC.setBorder(null);
        jtEmailC.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtEmailCFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtEmailCFocusLost(evt);
            }
        });
        pnlRegistrar.add(jtEmailC, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 220, 40));

        jtPassC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtPassC.setText("Contraseña");
        jtPassC.setBorder(null);
        jtPassC.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtPassCFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtPassCFocusLost(evt);
            }
        });
        pnlRegistrar.add(jtPassC, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 220, 40));

        btnRegistrarseC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesLogin/btnRegistrarse.png"))); // NOI18N
        btnRegistrarseC.setBorderPainted(false);
        btnRegistrarseC.setContentAreaFilled(false);
        btnRegistrarseC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarseCActionPerformed(evt);
            }
        });
        pnlRegistrar.add(btnRegistrarseC, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, -1, -1));

        cards.add(pnlRegistrar, "card2");

        getContentPane().add(cards, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 350, 390));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        cards.removeAll();
        cards.add(pnlIngresar);
        cards.repaint();
        cards.revalidate();
        cardSelected();  
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarseActionPerformed
        cards.removeAll();
        cards.add(pnlRegistrar);
        cards.repaint();
        cards.revalidate();
        cardSelected();
    }//GEN-LAST:event_btnRegistrarseActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnOlvidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOlvidarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOlvidarActionPerformed

    private void jtUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtUsuarioFocusGained
        if(jtUsuario.getText().equals("E-mail")){
            jtUsuario.setText("");
        }
    }//GEN-LAST:event_jtUsuarioFocusGained

    private void jpsPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jpsPassFocusGained
        char pass[] = jpsPass.getPassword();
        String password = new String(pass);
        if(password.equals("$$$$$$$$$$$$$")){
            jpsPass.setText("");
        }
    }//GEN-LAST:event_jpsPassFocusGained

    private void jtUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtUsuarioFocusLost
        if(jtUsuario.getText().equals("")){
            jtUsuario.setText("E-mail");
        }
    }//GEN-LAST:event_jtUsuarioFocusLost

    private void jpsPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jpsPassFocusLost
        char pass[] = jpsPass.getPassword();
        String password = new String(pass);
        if(password.equals("")){
            jpsPass.setText("$$$$$$$$$$$$$");
        }
    }//GEN-LAST:event_jpsPassFocusLost

    private void btnAccederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccederActionPerformed
        int resul;
        if(jtUsuario.getText().equals("E-Mail") || jtUsuario.getText().equals("") || jpsPass.getText().equals("") || jpsPass.getText().equals("$$$$$$$$$$$$$")){
            JOptionPane.showMessageDialog(null, "Rellene todo los campos");
        }else{
            try {
                Statement sql = Conexion.getConnection().createStatement();

                String consulta = "SELECT U.NOMBRE_USUARIO FROM USUARIO AS U WHERE U.EMAIL='" + jtUsuario.getText() + "' AND PASSWORD='" + jpsPass.getText() + "'";
                ResultSet resultado = sql.executeQuery(consulta);

                if (resultado.next()) {
                    resul = 1;
                    nUsuario=resultado.getString(1);
                }else{
                    resul=0;
                }
                
                if(resul==1){
                    MenuPrincipal ventana = new MenuPrincipal();
                    ventana.setVisible(true);
                    this.dispose();
                }else{
                    JOptionPane.showMessageDialog(null, "Datos de la cuenta invalidos");
                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Datos de la cuenta invalidos");
            }
        }
    }//GEN-LAST:event_btnAccederActionPerformed
    private boolean existeUsuario(String user){
        boolean existe=false;
        try {
            Statement sql = Conexion.getConnection().createStatement();

            String consulta = "SELECT * FROM USUARIO AS U WHERE U.NOMBRE_USUARIO='" + user + "'";
            ResultSet resultado = sql.executeQuery(consulta);

            if (resultado.next()) {
                existe = true;
            } else {
                existe = false;
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Datos de la cuenta invalidos");
        }
        
        return existe;
    }

    //Mover el frame
    int xx,xy;
    private void topHeadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topHeadMousePressed
        xx=evt.getX();
        xy=evt.getY();
    }//GEN-LAST:event_topHeadMousePressed

    private void topHeadMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topHeadMouseDragged
        int x= evt.getXOnScreen();
        int y= evt.getYOnScreen();
        
        this.setLocation(x-xx, y-xy);
    }//GEN-LAST:event_topHeadMouseDragged

    private void btnRegistrarseCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarseCActionPerformed
        if (jtUsuarioC.getText().equals("Nombre de Usuario") || jtNombreC.getText().equals("Nombre y Apellido") || jtEmailC.getText().equals("E-mail") || jtPassC.getText().equals("Contraseña")) {
            JOptionPane.showMessageDialog(null, "Rellene todo los campos");
        } else {
            if (!existeUsuario(jtUsuarioC.getText())) {
                try {
                    String consulta = "INSERT INTO USUARIO VALUES ('" + jtUsuarioC.getText() + "','" + jtNombreC.getText() + "','" + jtEmailC.getText() + "','" + jtPassC.getText() + "')";

                    PreparedStatement sql = Conexion.getConnection().prepareStatement(consulta);

                    sql.executeUpdate();

                    JOptionPane.showMessageDialog(null, "Usuario creado correctamente!");
                    cards.removeAll();
                    cards.add(pnlIngresar);
                    cards.repaint();
                    cards.revalidate();
                    cardSelected();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, ex.toString());
                }
            } else {
                JOptionPane.showMessageDialog(null, "El nombre de usuario que eligió ya existe, por favor elija otro");
            }
        }
    }//GEN-LAST:event_btnRegistrarseCActionPerformed

    private void jtUsuarioCFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtUsuarioCFocusGained
        if(jtUsuarioC.getText().equals("Nombre de Usuario")){
            jtUsuarioC.setText("");
        }
    }//GEN-LAST:event_jtUsuarioCFocusGained

    private void jtUsuarioCFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtUsuarioCFocusLost
        if(jtUsuarioC.getText().equals("")){
            jtUsuarioC.setText("Nombre de Usuario");
        }
    }//GEN-LAST:event_jtUsuarioCFocusLost

    private void jtNombreCFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNombreCFocusGained
        if(jtNombreC.getText().equals("Nombre y Apellido")){
            jtNombreC.setText("");
        }
    }//GEN-LAST:event_jtNombreCFocusGained

    private void jtNombreCFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNombreCFocusLost
        if(jtNombreC.getText().equals("")){
            jtNombreC.setText("Nombre y Apellido");
        }
    }//GEN-LAST:event_jtNombreCFocusLost

    private void jtEmailCFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtEmailCFocusGained
        if(jtEmailC.getText().equals("E-mail")){
            jtEmailC.setText("");
        }
    }//GEN-LAST:event_jtEmailCFocusGained

    private void jtEmailCFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtEmailCFocusLost
        if(jtEmailC.getText().equals("")){
            jtEmailC.setText("E-mail");
        }
    }//GEN-LAST:event_jtEmailCFocusLost

    private void jtPassCFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtPassCFocusGained
        if(jtPassC.getText().equals("Contraseña")){
            jtPassC.setText("");
        }
    }//GEN-LAST:event_jtPassCFocusGained

    private void jtPassCFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtPassCFocusLost
        if(jtPassC.getText().equals("")){
            jtPassC.setText("Contraseña");
        }
    }//GEN-LAST:event_jtPassCFocusLost

    private void cardSelected(){
        Component panel = cards.getComponent(0);
        if(pnlIngresar==panel){
            ImageIcon imagen = new ImageIcon(getClass().getResource("/imagenesLogin/btnIngresarActivo.png"));
            btnIngresar.setIcon(imagen);
            
            ImageIcon imagen2 = new ImageIcon(getClass().getResource("/imagenesLogin/btnRegistrarsInac.png"));
            btnRegistrarse.setIcon(imagen2);
        }else{
            ImageIcon imagen = new ImageIcon(getClass().getResource("/imagenesLogin/btnIngresarInactivo.png"));
            btnIngresar.setIcon(imagen);
            
            ImageIcon imagen2 = new ImageIcon(getClass().getResource("/imagenesLogin/btnRegistrarseActivo.png"));
            btnRegistrarse.setIcon(imagen2);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcceder;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnOlvidar;
    private javax.swing.JButton btnRegistrarse;
    private javax.swing.JButton btnRegistrarseC;
    private javax.swing.JPanel cards;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jpsPass;
    private javax.swing.JTextField jtEmailC;
    private javax.swing.JTextField jtNombreC;
    private javax.swing.JTextField jtPassC;
    private javax.swing.JTextField jtUsuario;
    private javax.swing.JTextField jtUsuarioC;
    private javax.swing.JPanel pnlIngresar;
    private javax.swing.JPanel pnlRegistrar;
    private javax.swing.JPanel topHead;
    // End of variables declaration//GEN-END:variables
}
